pod 'MBProgressHUD'
pod 'Facebook-iOS-SDK'
pod 'libPusher', '~> 1.4'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'Helpshift', '~> 4.3'
pod 'CocoaLumberjack', '~> 1.8'
pod 'PubNub', '~> 3.6'
pod 'Reachability', '~> 3.1.0'
